# Generated by Django 5.0.6 on 2024-06-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
